### ISSUE TITLE
Error UI polish

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3982]
We've had a chance to iterate on our designs a bit and there are a few items that need to be addressed to get things matching the mocks.

See [https://highlightcorp.slack.com/archives/C046SEE53HP/p1673368341884969](https://highlightcorp.slack.com/archives/C046SEE53HP/p1673368341884969) for more context.

Related issues:

```[tasklist]
### Tasks
- [ ] #3984
- [ ] #4037
- [ ] #3983
- [ ] #4064
- [x] Loading state should be centered
- [x] Next/previous instance buttons' content should be centered
- [x] Remove unnecessary scrollbars on stacktrace sourcemaps tooltip
```

**Comment by ccschmitz** [comment]
@julian-highlight I made [#4138](https://github.com/highlight/highlight/issues/4138) as a follow up on that!

**Comment by ccschmitz** [comment]
Oh, does #4037 cover what you were thinking?

**Comment by julian-highlight** [comment]
@ccschmitz oh yea, that's exactly what I've meant! Sorry
