### ISSUE TITLE
Weird Stacktrace (Stack trace) Issues

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4222]
```[tasklist]
### Tasks
- [x] https://app.highlight.io/1/errors/747rEjVvVEN0MUiHaj0ebOp302x7?page=1 <img width="1057" alt="image" src="https://user-images.githubusercontent.com/20292680/217943140-25a7e233-3d19-42ee-babc-a84254ac092f.png">
- [x] https://app.highlight.io/1/errors/ms7U1pwOsBoyV9SWmpnYIoHrtIQI?page=1 <img width="1183" alt="image" src="https://user-images.githubusercontent.com/20292680/217943490-363e8ec3-d988-4511-97ff-92ed9f1b26de.png">
- [x] https://app.highlight.io/1/errors/1bX1y5STkHvSNuLeXPvEPY9W4mvV?page=1 <img width="1071" alt="image" src="https://user-images.githubusercontent.com/20292680/217967824-c9ae31ae-f2b5-459b-864a-77aabf862fef.png">
- [x] https://app.highlight.io/1/errors/b7X5nMvxwDx835jaYe58VVGjeFth?page=1 <img width="1329" alt="image" src="https://user-images.githubusercontent.com/20292680/218338034-e7cf82fe-90a9-466a-8fa8-d4fb00754248.png">
- [x] https://app.highlight.io/1/errors/E08h6HgQrDBzn0e90ID13WZ0Qm4N?page=1 <img width="1143" alt="image" src="https://user-images.githubusercontent.com/20292680/218568418-b720421c-2dee-4878-b1e6-f7c07b5ecfdf.png">
- [x] https://app.highlight.io/1/errors/RxxaYWFKZPsIa1lF1phmFqTQ04BO <img width="1110" alt="image" src="https://user-images.githubusercontent.com/20292680/218578847-5d5e6ce9-47bc-4744-9528-52924661c624.png">
- [ ] https://app.highlight.io/1/errors/SyhSBjTeDOf1f0SLoSy2HxVhumGx?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C30%20days <img width="998" alt="image" src="https://user-images.githubusercontent.com/20292680/218920191-01983fe2-859b-4b63-bd7e-b7eea6b85ed2.png">
```

**Comment by jay-khatri** [comment]
@Vadman97 , added 3-4 more errors her.
