### ISSUE TITLE
Feedback from Resend

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#4238]
They shared [a doc](https://resend.notion.site/resend/Highlight-Friction-Log-3ade2e0987704882ab5860f9ca3110db) with some super helpful feedback on friction points in the sign up / setup process. We should work through these changes.

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5118
- [ ] https://github.com/highlight/highlight/issues/5119
- [x] Make sure form doesn't reset on failed submission
- [x] Review which framework is most used and consider reordering tabs on `/setup`
- [x] For Next.js and other frameworks with a consistent app structure, mention file names that should be modified
- [x] Make sure "View Session" button works from `/setup`
- [ ] https://github.com/highlight/highlight/issues/4288
- [x] Make sure adding Vercel doesn't prompt to create a new workspace
- [ ] https://github.com/highlight/highlight/issues/4247
- [x] See if we can streamline setup of wrapping code `withHighlight`
- [ ] https://github.com/highlight/highlight/issues/5113
- [x] Fix broken links to docs
```

**Comment by ccschmitz** [comment]
@jay-khatri there are a couple tasks outstanding from this, but there are separate open issues tracking their progress. I'm going to close this issue out.
