### ISSUE TITLE
Error Boundary Updates & Enhancements

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4288]
```[tasklist]
### Tasks
- [x] Cleanup UI for Error Boundary w/ new UI components
- [ ] Send crash (or "feedback") alerts via the "normal" error alerts: https://github.com/highlight/highlight/issues/4663
- [ ] https://github.com/highlight/highlight/issues/4289
- [x] Styling issues in certain environments: https://github.com/highlight/highlight/issues/4641
```

**Comment by jay-khatri** [comment]
Also, We have "feedback" alerts in Highlight right now, which is what triggers a feedback modal submission. I'm thinking:
- get rid of these alerts (bundle everything in "error alerts").
- come up with a way to represent this feedback in the `error` model and pipe it through there
- make sure that visually, this works. i.e. in the session UI, this should look ok. I think the easy thing to do would be

**Comment by Vadman97** [comment]
@julian-highlight is there a design for the new error boundary and the rest of this cleanup?

**Comment by Vadman97** [comment]
@julian-highlight this is what the error boundary currently looks like 

![Image](https://user-images.githubusercontent.com/1351531/224798977-d075137c-6f42-4027-89ac-0f21302c5766.png)

**Comment by julian-highlight** [comment]
@Vadman97 
Created an updated version fitting to our sign up flow. While making the inputs feel more on point, I've also changed the bottom CTA section. Generally you always want to have the primary action last in modals like this. Therefor it's on the far right. Created a little badge for our logo, which feels more clean now. Do we also need a mobile version for the modal? 

![image](https://user-images.githubusercontent.com/114743131/225015304-0b2a0f13-d24a-4bc9-99d0-736998f7bcfd.png)


https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6497%3A545280&t=7X2TqLTHk2SuKUPq-11

CC @aaronmaxcarver

**Comment by jay-khatri** [comment]
@julian-highlight we just added a design for this correct? mind linking the figma here?

**Comment by julian-highlight** [comment]
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6496%3A270900&t=0jLkz48G9XFCSLUe-11
@jay-khatri (it's in the comment above)
