### ISSUE TITLE
Polish the JSON view on logging

### ISSUE THREAD

**Issue by et** [highlight/highlight#4341]
```[tasklist]
### Tasks
- [x] Polish the JSON view per [Figma](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=5295%3A236374)
- [x] Only show relevant log data (e.g. we shouldn't be showing `__typename`) -- simply show the structured data that was sent from the log
- [x] Add a copy button
- [x] Allow toggling expansion of nested logs
- [x] Collapse all log rows on search
```
