### ISSUE TITLE
support enterprise self-hosting

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4390]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6456
- [ ] openshift deploy config
- [ ] AWS cloudformation template
- [ ] terraform deploy
```

**Comment by mateothegreat** [comment]
I'd consolidate all of:

- argo helm chart for kubernetes deployments
- openshift deploy config
- AWS cloudformation template
- terraform deploy

...in to small units of work (frontend, then backend, then kafa, etc..) that combined make a composition highlight deployment that become configuration variables that roll up to the top.

The most complicated pieces are the infrastructure services like kafka and getting them _right_ as they each have their own significant challenges to achieve fault tolerance and scalability.

I think the easiest path forward would be to focus on helm and use components as dependencies so ya'll can focus on delivering value in highlight vs. maintaining expectations with all of these external dependencies.
