### ISSUE TITLE
Log match should highlight when in expanded json

### ISSUE THREAD

**Issue by et** [highlight/highlight#4469]
```[tasklist]
### Tasks
- [ ] Fix highlighting when using wildcards (`*`)
- [ ] Highlight matches in nested content
- [ ] Don't toggle row when trying to select text
```

![Screenshot_2023-03-02_at_3_01_04_PM](https://user-images.githubusercontent.com/58678/222568633-5c736708-14fb-41f7-b57a-e257a56a1202.png)

We should also get highlighting working for substrings. e.g. if the search value is `*session*`, we should match on everything with `session` in it.
