### ISSUE TITLE
Setup E2E testing pipeline of SDKs

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4588]
Here's how I propose we tackle this:
use the `docker` test to validate SDKs
1. run docker stack
2. build a pytest setup that can do a `yarn dev`, `poetry run flask run`, `go run main.go` etc to spin up `e2e` directory apps
3. use `requests` in the pytests to hit backend endpoints of the e2e apps
4. each `e2e` directory app emits it's own signature error that we can check for in the locally running highlight instance

we can start by adding this for one SDK, eg `nodejs`. subsequently, we will have one pytest testcase per SDK setup

```[tasklist]
### Tasks
- [ ] electron main thread event listeners / sendBeacon test
- [ ] test SDK service names, related to #4743
- [ ] setup highlight.run cjs / umd test (validate <script> tag usage and vite-ssr)
```
