### ISSUE TITLE
Q2 2023 Roadmap Brainstorm

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#4692]
The theme: Get people started + fully onboarded.

```[tasklist]
### \[Product] Session Viewer - Chris
- [ ] https://github.com/highlight/highlight/issues/4517
- [ ] https://github.com/highlight/highlight/issues/4895
- [ ] session viewer 👇
- [ ] SR: Revamp Session Comments + Delete Notifications
- [ ] SR: Add rage clicks to session viewer
- [ ] SR: Make timeline indicator bar width the same all the time #3921
- [ ] SR: Add draggable handle to session viewer (can't drag right now)
- [ ] SR: Inspect Element: Inspect element mode is non-obvious (have to click "d")
- [ ] SR: `cursor: pointer` on network requests and errors to make them clearly clickable
- [ ] How do I create a comment? Its not clear
- [ ] Live mode 👇
- [ ] https://github.com/highlight/highlight/issues/4965
- [ ] group request + logs + errors on session viewer 👇
- [ ] https://github.com/highlight/highlight/issues/4784
- [ ] Cohesion: Render backend logs on the replay viewer (in the network request context + console logs context)
- [ ] Cohesion: Pair network requests w/ errors on the replay view
- [ ] In the error feed on a session view, click to “view in error feed”
- [ ] https://github.com/highlight/highlight/issues/4704
- [ ] To Ticket 👇
```

```[tasklist]
### Logging - Eric
- [ ] https://github.com/highlight/highlight/issues/4881
- [ ] Fly.io, AWS, Filebeat, etc.. #4450
```

```[tasklist]
### \[Product] Error Monitoring - Eric
- [ ] https://github.com/highlight/highlight/issues/4980
- [ ] https://github.com/highlight/highlight/issues/4966
- [x] Fix nextjs integration
- [x] EM: More aggressive error grouping + exponential alerting
- [x] https://github.com/highlight/highlight/issues/5103
- [x] Improvements to our error boundary
- [ ] https://github.com/highlight/highlight/issues/5051
- [ ] https://github.com/highlight/highlight/issues/4656
- [ ] #4966
```

```[tasklist]
### Session/Error search filtering - Zane
- [ ] https://github.com/highlight/highlight/issues/5040
- [ ] https://github.com/highlight/highlight/issues/5041
- [ ] https://github.com/highlight/highlight/issues/5038
- [ ] https://github.com/highlight/highlight/issues/5039
- [ ] https://github.com/highlight/highlight/issues/5037
- [ ] https://github.com/highlight/highlight/issues/4886
- [ ] https://github.com/highlight/highlight/issues/4093
```

```[tasklist]
### \[Product] Future Work (Q3+)
- [ ] FW: Flame graphs for traces
- [ ] EM: Have the ability to search by resources based on requests
- [ ] https://github.com/highlight/highlight/issues/4783
```

```[tasklist]
### Internal Eng
- [ ] demo account
- [ ] Billing updates
- [ ] https://github.com/highlight/highlight/issues/4787
- [ ] Upgrade our internal JS bundle to start using OTEL in preparation for doing frontend traces
- [ ] Add ability to log in via email/password in dev
- [ ] https://github.com/highlight/highlight/issues/4588
- [ ] https://github.com/highlight/highlight/issues/4785
- [ ] https://github.com/highlight/highlight/issues/4788
- [ ] https://github.com/highlight/highlight/issues/4803
- [ ] https://github.com/highlight/highlight/issues/4912
- [ ] https://github.com/highlight/highlight/issues/5052
- [ ] https://github.com/highlight/highlight/issues/4942
- [ ] Enterprise Deploy / Self-hosting?
```

```[tasklist]
### \[Design] Updates
- [ ] Alerts page
- [ ] https://github.com/highlight/highlight/issues/4917
- [x] Notifications
- [ ] (Filter) menus
- [ ] Dashboards
- [ ] Analytics
- [ ] Modals
- [ ] https://github.com/highlight/highlight/issues/5138
- [ ] Switch Workspace
- [ ] Shortcuts
- [ ] Popup alerts
- [ ] Menu behavior
```

```[tasklist]
### [Design] New
- [ ] Dark theme
- [ ] Graph Color System + Tokens
- [ ] Selected state tokens
- [ ] Effects as tokens
```

```[tasklist]
### \[Design] Polish
- [ ] Improve Font legibility & spacing
- [ ] Improve Session toolbar (Declutter...)
- [ ] Improve List items (Generalize style + Improve Layouts)
- [ ] Component variant naming should be identical to prod
- [ ] Add leading trim to the design system (Figma)
```
