### ISSUE TITLE
Polishing Logs 2.0

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#4747]
Another list of tickets to polish the overall experience of logs. 
@jay-khatri kindly recorded a small [loom video](https://www.loom.com/share/091f248f0b63488ba9b778a494a052df) covering most of the tickets seen in the tasklist below. 

```[tasklist]
### Tasks
- [x] https://github.com/highlight/highlight/issues/4896
- [x] Resolve clearing queries bug, to not update the data
- [x] Add Chevron to 'Custom' item on the time dropdown to show that there's another menu hidden behind this option
- [ ] https://github.com/highlight/highlight/issues/4754
- [ ] https://github.com/highlight/highlight/issues/4799
- [x] clicking bar graphql level should add to the query
- [ ] https://github.com/highlight/highlight/issues/4874
- [ ] https://github.com/highlight/highlight/issues/4891
- [ ] https://github.com/highlight/highlight/issues/4903
```

**Comment by jay-khatri** [comment]
@ccschmitz added you to the high-level issue. For the loading/end state, added @et.
