### ISSUE TITLE
Frontend tech debt

### ISSUE THREAD

**Issue by et** [highlight/highlight#4785]
```[tasklist]
### Tasks
- [ ] Deprecate all usages of `<ButtonLink />` and replace with `<LinkButton />`
- [ ] Validate all usages of `<LinkButton />` and see if they can use the `iconLeft` and `iconRight` props over defining a `<Box />` inline ([example](https://github.com/highlight/highlight/blob/f49df1886d0f01bbf838344957afd9c9d49c4925/frontend/src/pages/LogsPage/LogsTable/LogDetails.tsx#L253-L268) of something that can change).
- [ ] https://github.com/highlight/highlight/issues/4790
```
