### ISSUE TITLE
Competitor Page Updates

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#4987]
```[tasklist]
### Tasks
- [x] Update Headline to use H4 instead of H2
- [x] Add title to text section underneath table
- [x] Update Titles in the Text Section to use H5 instead of H4
- [ ] We think the line-height is incorrect for the competitor pages
- [ ] Migrate all content from google doc
- [ ] Add tooltips
```

Loom from @jay-khatri https://www.loom.com/share/8a798937ab6c4161b5ac2ded6182577d
