### ISSUE TITLE
vue.js + node.js firebase fn DX

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4991]
vue.js - [highlight.run](http://highlight.run/) + highlight-run/sourcemap-uploader + node.js firebase fn

```[tasklist]
### Tasks
- [ ] functions.logger is not sending logs to highlight
- [ ] make docs use consistent import/require syntax
- [ ] make it obvious where to put h.init
- [ ] npm install --save sdks
- [ ] cors setup for highlight header
- [ ] tracingOrigins: ['localhost:4000', 'https://us-central1-highlight-f5c5b.cloudfunctions.net']
```

https://www.loom.com/share/d0e5b378cbc74550bb59f232034dd8c7
