### ISSUE TITLE
vue.js + node.js apollo DX

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4992]
vue.js - [highlight.run](http://highlight.run/) + highlight-run/sourcemap-uploader + node.js apollo

```[tasklist]
### Tasks
- [ ] H.identify example does not work in vue.js
- [ ] sourcemap uploader needs vite config changes
- [ ] vue.js should set tracing origins
- [ ] apollo node sdk should show where (what file) to put h.init
- [ ] frontend session right panel error view metadata expand overflows
- [ ] logs show option for session_secure_id and secure_session_id
```

https://www.loom.com/share/5aed9dd8a56b4a128137e855c11f094e
https://www.loom.com/share/32cf10df4bf14b11bd284420422039bb
https://github.com/highlight/dx-check-vue-apollo-graphql

cc @jay-khatri

**Comment by Vadman97** [comment]
```yarn dlx @highlight-run/sourcemap-uploader upload --apiKey $HIGHLIGHT_SECRET --path ./dist```

**Comment by CatherineKiiru** [comment]
Hello Vadman, I'd like to contribute to Highlight. Are there any more issues you'll be posting soon?

**Comment by Vadman97** [comment]
Hey @CatherineKiiru , all issues labeled [good-first-issue](https://github.com/highlight/highlight/labels/good%20first%20issue) are great ones for getting started. We also have some [docs on contributing here](https://www.highlight.io/docs/general/company/open-source/contributing/getting-started) and a helpful [community on discord](https://highlight.io/community). Let us know how we can help!
