### ISSUE TITLE
session player ui improvements

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5044]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5140
- [ ] https://github.com/highlight/highlight/issues/5141
- [ ] https://github.com/highlight/highlight/issues/5142
- [ ] https://github.com/highlight/highlight/issues/5146
- [ ] https://github.com/highlight/highlight/issues/4964
- [x] SR: Add rage clicks to session viewer
- [ ] https://github.com/highlight/highlight/issues/5143
- [ ] https://github.com/highlight/highlight/issues/5145
- [ ] https://github.com/highlight/highlight/issues/5171
```
