### ISSUE TITLE
session player cohesion improvements (network request view)

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5045]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5207
- [ ] https://github.com/highlight/highlight/issues/4784
- [ ] https://github.com/highlight/highlight/issues/5208
- [ ] https://github.com/highlight/highlight/issues/5209
- [ ] https://github.com/highlight/highlight/issues/5139
```
