### ISSUE TITLE
improve 'publicly shared with web' session / errors sharing

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5050]
```[tasklist]
### Tasks
- [ ] cleanup ui of unlisted session
- [ ] cleanup ui of unlisted error
- [ ] add to e2e cypress test: populate a session and error, click `share with web` on each, ensure they load in incognito
```
