### ISSUE TITLE
SR: Revamp Session Comments

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5140]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5186
- [ ] https://github.com/highlight/highlight/issues/5187
- [ ] https://github.com/highlight/highlight/issues/3924
- [ ] https://github.com/highlight/highlight/issues/5188
```

Mocks: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=4989%3A215023&t=xOVueQzDyYLRMDLY-1
