### ISSUE TITLE
If `version` is incorrectly instrumented, do our best to match.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5432]
In the case that a customer doesn't report `version` correctly, we should do a better job of matching to the latest version of their sourcemap. 

cc @Vadman97 @et 

https://highlightcorp.slack.com/archives/C02CJANPHQS/p1685506427227599
```[tasklist]
### Tasks
- [ ] Create table of source maps that is inserted when uploaded to s3
- [ ] Fetch latest source map when no linked source map
- [ ] Display info on UI about source map used and method to find
```
