### ISSUE TITLE
Make the date picker more usable

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5452]
Make the date picker more usable:
https://www.notion.so/runhighlight/date-picker-audit-b4c5b85d347e46a593d7707825bf815a?pvs=4

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5489
- [ ] https://github.com/highlight/highlight/issues/5490
- [ ] https://github.com/highlight/highlight/issues/5491
- [ ] https://github.com/highlight/highlight/issues/5492
```

**Comment by jay-khatri** [comment]
@julian-highlight do you mind extracting these into issues?

**Comment by julian-highlight** [comment]
Sure! Here's a tasklist. Adding a few comments into the issues! 

- [ ] Add disabled state for disabled days 
- [ ] Enable inputs
- [ ] Remove hover jiggle
- [ ] Use component styling
