### ISSUE TITLE
miscellaneous customer feedback on the onboarding experience

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5462]
https://discord.com/channels/1026884757667188757/1111459644053921822

```[tasklist]
### Tasks
- [ ] copy button in setup is useless since it copies npm and yarn instructions. add pnpm
- [ ] replace `<YOUR_PROJECT_ID>` useless since it is already replaced
- [ ] urlBlocklist should have an example or be omitted since it is not frequently used ```
```
