### ISSUE TITLE
Improve error instances UX

### ISSUE THREAD

**Issue by et** [highlight/highlight#5476]
```[tasklist]
### Tasks
- [x] Add [designs](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9061-220004&t=5o5Zvjvl9WWChWvN-11)
- [x] Add backend support to fetch a list error instances (#5557)
- [ ] https://github.com/highlight/highlight/issues/5586
- [ ] https://github.com/highlight/highlight/issues/5599
- [ ] Update navigation between error instances
- [ ] https://github.com/highlight/highlight/issues/5850
```

**Comment by et** [comment]
Designs: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=8467-349352&t=hysbCe8T5ZWlQ8s9-11

**Comment by julian-highlight** [comment]
Btw @et 
I've made some smaller changes to the designs today to simplify the instance-detail view. Let me know if you touched that already, or if you got any questions. 

Link: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9061-220004&t=5o5Zvjvl9WWChWvN-11
