### ISSUE TITLE
Unresolving errors is getting out of sync with opensearch

### ISSUE THREAD

**Issue by et** [highlight/highlight#5511]
![Screenshot_2023-06-01_at_1_59_23_PM](https://github.com/highlight/highlight/assets/58678/26a5bd98-f9a3-45fe-8aff-77f397565ad0)

It seems like when an error state is updated, postgres and opensearch aren't in sync.

Tasks

- [x] Retry sync updates on conflict (#5530)
- [x] Skip retries on sync flow (#5528)
- [x] Make public graph requests sync (#5524)
- [x] Make private graph requests sync (#5531)
- [ ] Make worker requests sync
- [ ] Remove async update (#5539) (will solve #5457)
- [ ] Ensure there are no more [OPENSEARCH_ERROR](https://app.highlight.io/1/logs?query=OPENSEARCH_ERROR) logs
- [ ] Remove async index
- [ ] Reindex error groups
