### ISSUE TITLE
Error Triaging Improvements

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5614]
```[tasklist]
### Tasks
- [ ] #5613
- [ ] Decide on error monitoring alert defaults and ensure that any new workspaces use those defaults
- [ ] opt-in feature to auto-create issue tracker tickets for each new error group that are auto-assigned to a rotation of users
- [ ] #5615
- [ ] https://github.com/highlight/highlight/issues/5655
```

**Comment by ccschmitz** [comment]
Closing this in favor of #5649.
