### ISSUE TITLE
AI error resolution suggestions

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5620]
```[tasklist]
### Tasks
- [x] (Backend) Golang Sdk
- [x] (Backend) Query
- [x] (Backend) Getting relevant data to make query
- [x] (Frontend) When to call query
- [x] (Frontend) Display info
```

## Dev Notes

* ChatGTP docs
  * https://platform.openai.com/docs/guides/gpt/chat-completions-api
  * https://platform.openai.com/docs/api-reference/chat
* Roles
  * `system` - Use this to guide the model's behavior throughout the conversation. e.g. "You are a software engineer helping debug an error."
  * `user` - Share context about our issue.
* Go SDK: https://github.com/sashabaranov/go-openai
