### ISSUE TITLE
[Brainstorm] Errors product changes

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5649]
```[tasklist]
### Tasks
- [ ] Release management
- [ ] Anomoly detection (+ spike detection)
- [ ] Enhance stack traces with metadata from GitHub
- [ ] Auto assign issues (possibly based on git blame)
- [ ] Throttling for Slack/Discord/email alerts
- [ ] Relevance score for errors
- [ ] Improve Slack/Discord/email alert content (add more info, link to configure alert, etc.)
- [ ] Surface activity log on errors
- [ ] AI-generated code changes (auto-revert based on anomalies)
- [ ] Incident/alert/anomaly pages
- [ ] Resolution notifications / celebrations
- [ ] Fix existing bugs (notifications, stack traces, etc.)
- [ ] https://github.com/highlight/highlight/issues/5655
- [ ] https://github.com/highlight/highlight/issues/5615
- [ ] Decide on error monitoring alert defaults and ensure that any new workspaces use those defaults
- [ ] opt-in feature to auto-create issue tracker tickets for each new error group that are auto-assigned to a rotation of users
- [ ] https://github.com/highlight/highlight/issues/5613
- [ ] https://github.com/highlight/highlight/issues/5703
- [ ] https://github.com/highlight/highlight/issues/5704
- [ ] https://github.com/highlight/highlight/issues/5432
```

Agreed this quarter will focus on troubleshooting individual errors. Will think about new functionality to cut through noise (anomaly detection) in the future.

## Metrics

* How are users engaging with the errors product?
  * Which parts of the page are being used?
* What's the distribution of resolved/snoozed/ignored errors?
* Are people who use the errors product more likely to become paid customers?
