### ISSUE TITLE
AI Suggestion Updates (V2)

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#5701]
We are rolling out Harold, the AI helper to all paid customers as a v1. Below are some of the improvements we want to make

```[tasklist]
### Tasks
- [ ] Docs for how the feature works (blog post + docs page)
- [ ] Add rate limiting (5/month for free customers)
- [ ] Reduce # of tokens sent for each request (trim stack trace)
- [ ] Store responses + feedback in Postgres (admin_id, project_id, feedback, prompt, reply - or maybe user feedback is stored in another table)
- [ ] Add CTA for upgrading when out of free credits
- [ ] Build a Hex dashboard for analyzing feature usage
- [ ] Show the previous result for an error on subsequent visits
```
