### ISSUE TITLE
Revamp panel for viewing an individual network request

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5735]
```[tasklist]
### Tasks
- [ ] Open existing request data in a new dialog
- [ ] https://github.com/highlight/highlight/issues/5852
- [ ] https://github.com/highlight/highlight/issues/5853
``` 

![Image](https://github.com/highlight/highlight/assets/308182/d1e1c37d-f0b4-4e17-8252-b03f906b21cb)

Mocks: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=8086%3A312347&mode=dev
