### ISSUE TITLE
logging ux improvemements

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5872]
hey, wanted to share two a few bugs i've come across lately with the logging product:

```[tasklist]
### Tasks
- [ ] date range doesn't reset to the latest when querying a new time range. @julian-highlight , can we add a refresh button to allow resetting the time range to requery data?
- [ ] https://github.com/highlight/highlight/issues/5999
- [ ] https://github.com/highlight/highlight/issues/6153
- [ ] https://github.com/highlight/highlight/issues/6162
- [ ] https://github.com/highlight/highlight/issues/6166
- [ ] https://github.com/highlight/highlight/issues/5529
- [ ] https://github.com/highlight/highlight/issues/6023
```

https://www.loom.com/share/328da2f2b12145b0bcd2c2fd05b75957

**Comment by julian-highlight** [comment]
What's holding us off from using relative timestamps here? Probably the same issue as of why a live view is hard to accomplish for now? From a UX perspective it would be great if there was no need for a UI solution here.

Totally get if we need to take smaller steps towards solving the problem, and I could see us add a little refresh icon next to the time information on the left! 

@et @ccschmitz

**Comment by Vadman97** [comment]
For 1. a little refresh icon makes sense as a first step.

**Comment by julian-highlight** [comment]
Added it here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=6344-268712&mode=design&t=BtQEGDmSjFj16UiZ-11 @Vadman97 

cc @ccschmitz
