### ISSUE TITLE
Traces Search

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5911]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6371
- [x] Use logs search UI components for seaching traces
- [ ] https://github.com/highlight/highlight/issues/6373
- [x] Backend for traces search
```

**Comment by jay-khatri** [comment]
https://highlightcorp.slack.com/archives/C059NFA87EG/p1691176890640129?thread_ts=1691083574.734399&cid=C059NFA87EG

<img width="1204" alt="image" src="https://github.com/highlight/highlight/assets/20292680/0a097f30-73c3-4b45-aa80-4363fb94ec2c">
