### ISSUE TITLE
Add new digests

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5918]
Seems like we have two types of emails we send out; a regular weekly digest for updates for that X, and a single email to get someone to view their first X. Lets do this for every product. Also, lets start tracking engagement on those things.

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6064
- [ ] https://github.com/highlight/highlight/issues/6063
- [ ] https://github.com/highlight/highlight/issues/6062
- [ ] https://github.com/highlight/highlight/issues/6061
- [ ] https://github.com/highlight/highlight/issues/5920
```

**Comment by jay-khatri** [comment]
take a quick peak at engagement from current session digest.
