### ISSUE TITLE
Introduce the Concept of Services

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5953]
link to full doc: https://www.notion.so/runhighlight/Services-PRD-75fc6fcff9614aa2a7dfccd4b6593f5b?pvs=4

<img width="760" alt="image" src="https://github.com/highlight/highlight/assets/20292680/59a9880e-111f-4efa-90c2-0d488b65f40e">

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5971
- [ ] https://github.com/highlight/highlight/issues/6045
- [ ] https://github.com/highlight/highlight/issues/6025
- [ ] https://github.com/highlight/highlight/issues/5970
- [x] If service_name or service_version passed from SDK, write property to error_groups or error_objects, respectively
- [ ] https://github.com/highlight/highlight/issues/6057
- [ ] https://github.com/highlight/highlight/issues/6168
- [ ] https://github.com/highlight/highlight/issues/6160
- [ ] https://github.com/highlight/highlight/issues/6159
- [ ] https://github.com/highlight/highlight/issues/6149
- [ ] https://github.com/highlight/highlight/issues/6206
- [ ] https://github.com/highlight/highlight/issues/6228
- [ ] https://github.com/highlight/highlight/issues/6250
- [ ] https://github.com/highlight/highlight/issues/5979
- [ ] https://github.com/highlight/highlight/issues/6200
- [ ] https://github.com/highlight/highlight/issues/6199
- [ ] https://github.com/highlight/highlight/issues/6098
- [ ] https://github.com/highlight/highlight/issues/6237
- [ ] https://github.com/highlight/highlight/issues/6449
- [ ] https://github.com/highlight/highlight/issues/6463
- [ ] https://github.com/highlight/highlight/issues/6465
```
