### ISSUE TITLE
GitHub enriched stack traces

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5954]
link to full doc: https://www.notion.so/runhighlight/GitHub-Integration-PRD-ac7d8fda396848b3a207a4ac5e61b8a5?pvs=4

<img width="739" alt="image" src="https://github.com/highlight/highlight/assets/20292680/eb786bf3-2af2-4f0b-963a-9c8cf5d7ea73">

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6069
- [ ] https://github.com/highlight/highlight/issues/6057
- [ ] https://github.com/highlight/highlight/issues/6070
- [ ] https://github.com/highlight/highlight/issues/6072
- [ ] https://github.com/highlight/highlight/issues/6123
- [ ] https://github.com/highlight/highlight/issues/6247
- [ ] https://github.com/highlight/highlight/issues/6285
```
