### ISSUE TITLE
Player Jittery Bugs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6178]
https://www.loom.com/share/124406fb67244fc88aab13fe898b3c1a
```[tasklist]
### Tasks
- [x] Player is Jittery (see loom above)
- [x] Clicking on a timestamp where the chunk hasn't loaded gives the user no feedback
- [x] Player time indicator is cached across session loads
- [x] turn off mouse trail by default
```

**Comment by jay-khatri** [comment]
another example: https://app.highlight.io/1/sessions/1TvZlkwV8wzKBLfJdqB7Fjhl1417?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-07-10T19%3A56%3A57.414Z_2023-08-09T19%3A56%3A57.414Z

This session doesn't play smoothly for me.

**Comment by jay-khatri** [comment]
@Vadman97 , if we could prioritize this for this week, that would be good. It seems to be getting worse. In particular, on a lot of sessions, when I pause in the middle of the session it takes me back to the beginning of it.

**Comment by jay-khatri** [comment]
anotha one (can't pause): https://app.highlight.io/1/sessions/agYfL3oW9VZ8dIcKz2A1orKlA61r?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-07-25T21%3A17%3A08.908Z_2023-08-24T21%3A17%3A08.908Z

**Comment by Vadman97** [comment]
#1 jumping back to start - seems to only happen with the auto-scroll console logs dev tools open

**Comment by Vadman97** [comment]
besides the 4 main bugs, looking into the render perf - we might have a regression that's causing us to repaint much more than we need to
<img width="895" alt="Screenshot 2023-09-11 at 8 02 19 PM" src="https://github.com/highlight/highlight/assets/1351531/676b1faa-a4e1-407c-a408-806281bf01f1">

**Comment by jay-khatri** [comment]
@Vadman97 something worth repro'ing: https://highlightcorp.slack.com/archives/C05N8NVL8AZ/p1694530572297479
