### ISSUE TITLE
Session Replay Player UI Updates

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6221]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6222
- [ ] https://github.com/highlight/highlight/issues/6223
- [ ] https://github.com/highlight/highlight/issues/6178
- [ ] https://github.com/highlight/highlight/issues/6089
- [ ] https://github.com/highlight/highlight/issues/4916
- [ ] https://github.com/highlight/highlight/issues/6276
- [ ] https://github.com/highlight/highlight/issues/6277
- [ ] https://github.com/highlight/highlight/issues/6278
```

**Comment by jay-khatri** [comment]
@ccschmitz assigned two of the above points to you if that's ok. Priority is relatively low, so feel free to grab them sometime this quarter.
