### ISSUE TITLE
Error Embeddings Launch

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6327]
```[tasklist]
### Tasks
- [ ] Build out MVP of Embeddings Demo
- [ ] Finalize Infra (error grouping + tagging)
- [ ] Write up H***er News post
- [ ] https://github.com/highlight/highlight/issues/6375
```
