### ISSUE TITLE
improve performance of querying for logs

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6329]
https://highlightcorp.slack.com/archives/C0454PWLLLW/p1691680130572079

current, the 30 day query is unusable, despite it starting from now. when you have nothing filtered, all queries should perform the same, since they should be starting loading the data that is most recent. in general, seems like the queries are inefficient per that slack thread.
```[tasklist]
### Tasks
- [x] improve histogram perf
- [x] improve field suggestions perf
- [ ] POC for multible sub queries for faster "first log" return
```
