### ISSUE TITLE
Log Alert message query bug

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6630]
https://discord.com/channels/1026884757667188757/1153121047491653762
<img width="523" alt="image" src="https://github.com/highlight/highlight/assets/20292680/832513c1-4d57-4b9d-a3c7-85635096d734">

```[tasklist]
### Tasks
- [x] When creating a log alert where the query is message:"any message here" or "any message here" the query ends up saving as "" with no value being inputted for the query.
- [x] when I delete a log alert I get a toast saying failed to delete, but after returning to the alert list and refreshing it was actually deleted.
- [x] Add a state check for query === "" to prevent an empty alert from being created
```

**Comment by anthonygregis** [comment]
I believe I found the issue with this bug.

It looks like we are using `formStore` on submission to create our input to the mutation, the issue with this is all other form inputs call `formStore.SetValue` on input change except for query. Query is only setting a local variable called `submittedQuery` that is not used when we call the create mutation. 

I'll draft a PR and test locally to ensure this is fixed

**Comment by anthonygregis** [comment]
This is going to need verification from someone else to confirm but I've been unable to actually get a lot alert to trigger even with a fixed query input locally.

On top of that I noticed that log alerts also lack the slack notifications that both session and error alerts get. This is evident in that the log alert create, update, delete resolvers do not contain the `sendWelcomeSlackMessage` that the other alerts utilize.

**Comment by mayberryzane** [comment]
Hi @anthonygregis - just confirmed I'm seeing the same issue. Log alerts are being evaluated, so I'm not sure what the exact root cause is but I'm looking into it today
