### ISSUE TITLE
Other Github stacktrace enhancement improvement ideas

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#6736]
```[tasklist]
### Tasks
- [x] Ability to save settings without repo
- [x] Add service to instance view (not obvious why errors are showing up on service filter)
- [x] Link to services page on first step
- [x] Update error trace with enhancement on save
- [ ] https://github.com/highlight/highlight/issues/6778
- [x] (Bug) After saving service for an error, the form of another error with the same service is blank
- [x] (Bug) Jankiness when opening the form - screen jumps around
```
