### ISSUE TITLE
Individual trace view refinements

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6820]
```[tasklist]
### Tasks
- [x] Clicking a span should select that space in the trace view, not the root
- [ ] https://github.com/highlight/highlight/issues/6851
- [x] Highlight spans with errors on flame graph
```
