### ISSUE TITLE
support environment as a first-party backend SDK attribute

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#7004]
all 4 products should report an `environment` along with the `service` and `service version`.
the motivation is to allow a given service (ie. `auth-api`) to be segmented by environment (`prod` vs `dev`) and have different ingest settings, or allow filtering out irrelevant data.
```[tasklist]
### Tasks
- [x] Report environment for backend errors
- [x] Add clickhouse migrations to support environment in features (traces/logs)
- [x] Report environment for logs
- [x] Report environment for traces
- [x] Add environment to Go SDKs
- [x] Add environment to Python SDKs
- [x] Add environment to Ruby SDKs
- [x] Add environment to Java SDKs
- [x] Add environment to Node SDKs
- [x] Add environment to NextJS
```

**Comment by jay-khatri** [comment]
to be more specific about what we want to support in the product once all of our sdks report environment:
- support for using `environment` in ingestion filters
- support for filtering by `environmnet` on all the search pages (logs, errors, traces, etc..)

**Comment by amitav13** [comment]
I'm a little confused with this - there's an environment property already that we're passing values to in the node and react SDKs on init. And within alerts there's a way to filter out alerts by environment - which doesn't work for us, but it is already in the dashboard. 

Has the functionality behind the 2 parts not been implemented?

**Comment by SpennyNDaJets** [comment]
Related PRs
- Support errors (use Go SDK as P.O.C): https://github.com/highlight/highlight/pull/7244/files
- Migrations: https://github.com/highlight/highlight/pull/7251
- Logs: https://github.com/highlight/highlight/pull/7245
- Traces: https://github.com/highlight/highlight/pull/7253

**Comment by SpennyNDaJets** [comment]
Python SDK: https://github.com/highlight/highlight/pull/7312
Javascript SDKs: https://github.com/highlight/highlight/pull/7322
Ruby SDK: https://github.com/highlight/highlight/pull/7318
