### ISSUE TITLE
SDK support for tracing

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7019]
Placeholder for improving tracing support in our SDKs.
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/7060
- [ ] https://github.com/highlight/highlight/issues/7061
- [ ] https://github.com/highlight/highlight/issues/7155
- [ ] https://github.com/highlight/highlight/issues/7233
- [ ] https://github.com/highlight/highlight/issues/7232
- [ ] https://github.com/highlight/highlight/issues/7067
```

**Comment by SpennyNDaJets** [comment]
Documentation structure doc: https://www.notion.so/runhighlight/Traces-Plans-832cca9c1f6346af92bd5c826a9fc623
