### ISSUE TITLE
Clean up loading state + stats on traces graphs

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7131]
```[tasklist]
### Tasks
- [x] Fix padding to be consistent with logs
- [x] Change format to `${label} ${stats}` on logs [more context](https://highlightcorp.slack.com/archives/C0454PWLLLW/p1699626634471919?thread_ts=1699400456.524279&cid=C0454PWLLLW)
- [x] Fix `Loading...` z-index so it doesn't appear over the typeahead results
```
