### ISSUE TITLE
Reflame feedback items

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7172]
Some feedback items from the Reflame team on their experience setting up tracing in Highlight so far. More context [in Slack](https://highlightcorp.slack.com/archives/C04DVJJ0ZJ6/p1699902000768529).

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/7208
- [ ] https://github.com/highlight/highlight/issues/7211
- [ ] https://github.com/highlight/highlight/issues/6922
- [ ] https://github.com/highlight/highlight/issues/7069
- [ ] https://github.com/highlight/highlight/issues/7153
- [ ] https://github.com/highlight/highlight/issues/7209
- [ ] https://github.com/highlight/highlight/issues/7210
```
