### ISSUE TITLE
Rework the Tracing Docs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#7232]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/7210
- [ ] https://github.com/highlight/highlight/issues/7233
- [ ] https://github.com/highlight/highlight/issues/7234
- [ ] https://github.com/highlight/highlight/issues/7235
- [ ] https://github.com/highlight/highlight/issues/7236
```
