### ISSUE TITLE
Trace empty state on network requests

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7438]
```[tasklist]
### Tasks
- [ ] Add loading state
- [ ] Add empty state when can't find trace
- [ ] Set max height on flame graph
- [ ] Move flame graph inside the Trace tab
```
