### ISSUE TITLE
Move unimportant trace attributes down in list

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7441]
Every trace has attributes like `ProjectID` that aren't very useful. We should move those down to the bottom of the list. Here's a list of attributes we know we should get out of the way.

* `ProjectID`

```
### Tasks
- [x] Format timestamp as a date
- [x] Move attributes to top: timestamp, span_name, duration, service_name, environment, service_version
- [x] Remove `ProjectID`
- [x] Remove empty values (`""`)
- [ ] Flatten nested values that contain a single value (e.g. `host.name: "..."`)
- [x] Move `traceAttributes` properties to the top level and remove that key
- [x] Demote default OTEL attributes: host, os, partition*, process
- [x] Convert stringified numbers to numbers
```

**Comment by ccschmitz** [comment]
I added the squashing of attributes to a single line if there is only one property in the object, but I actually wasn't sure if I liked it and wasn't confident in that change, so I left it out for now. We can always do that as another step, but I think this is already a big improvement!
